# Generated by Django 5.2.5 on 2025-08-19 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_banco', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banco_creado', to='usuario.usuario')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banco_actualizado', to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='BancoPais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paises', to='cuenta.banco')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancos', to='usuario.pais')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bancopais_creado', to='usuario.usuario')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bancopais_actualizado', to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas', to='cuenta.banco')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='usuario.moneda')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_creada', to='usuario.usuario')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_actualizada', to='usuario.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='usuario.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('fecha_expiracion', models.DateField()),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjetas', to='cuenta.banco')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='cuenta.cuenta')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjeta_creada', to='usuario.usuario')),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarjeta_actualizada', to='usuario.usuario')),
            ],
        ),
    ]
