# Generated by Django 5.2.5 on 2025-08-19 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='estado',
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('Ahorro', 'Ahorro'), ('Corriente', 'Corriente')], max_length=20),
        ),
    ]
