# Generated by Django 5.2.5 on 2025-08-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_remove_cuenta_estado_remove_tarjeta_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='bancopais',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='bancopais',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='user_create',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='user_update',
        ),
    ]
